spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/nh?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: tzh444582
  datasource:
    url: jdbc:mysql://124.222.139.8:3306/nh?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smtc
    password: 12345678


mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:mapper/*Xml.xml


server:
  #端口号
  port: 8082